#!/usr/bin/env ruby
#^syntax detection
 
site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'redisio'
cookbook 'database'
cookbook 'postgresql'
cookbook 'nginx'
# cookbook 'java'
# cookbook 'elasticsearch'
cookbook 'git'
cookbook 'python'
cookbook 'supervisor'
cookbook 'rabbitmq'
cookbook 'imagemagick'
